name: Run tests
on: [push]
defaults:
  run:
    shell: bash
jobs:
  run-test:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          check-latest: true
          cache: 'maven'
      - run: mvn clean package
